server:
  port: 8085
  servlet:
    context-path: /spring-boot-javers


spring:
  application:
    name: spring-boot-javers
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_javers?useSSL=false
    username: root
    password: babar123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect




#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

# Allows Hibernate to generate SQL optimized for a particular DBMS
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE

#server.servlet.context-path=/home-budget/api