server:
  port: 8085
  servlet:
    context-path: /spring-boot-javers


spring:
  application:
    name: spring-boot-javers
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_javers?useSSL=false
    username: root
    password: babar123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

